adding ER diagram
uc-cdis/arborist pull request #149
Opened 2022-05-02 19:53 UTC by pieterlukasse

Jira Ticket: N/A

### Improvements
- Added ERD to README

2023-04-27 16:48 UTC, Avantol13 submitted a review, later dismissed

2023-04-28 15:55 UTC, paulineribeyre requested changes
awesome! but can we create a new file in /docs and link to it in the readme, instead of making the readme longer? Like we do in more recent services, for example https://github.com/uc-cdis/requestor/blob/master/README.md#requestor

2023-05-01 18:11 UTC, pieterlukasse commented
@paulineribeyre that is a good idea. I've updated it accordingly.

2023-05-01 18:49 UTC, paulineribeyre approved these changes

2023-05-01 19:28 UTC, merged